#!/usr/bin/env php
<?php
//--------------------------------------------------------------------------------------------------
// Require Zero Core Processor
//--------------------------------------------------------------------------------------------------
//
// ZN Framework sınıf ve yöntemlerini kullanabilmeniz için kök dizinde yer alan zerocore adlı
// dosyayı kullanmak istediğiniz dosya içerisine require etmeniz gerekir.
//
//--------------------------------------------------------------------------------------------------
require_once 'zerocore';

//--------------------------------------------------------------------------------------------------
// Your Codes
//--------------------------------------------------------------------------------------------------
//
// Bu betiğe yazılan kodların kabuk ile çalıştırılabilmesi için aşağıdaki kullanımdan yararlanılır.
//
// Processor::file('Sample');
//
//--------------------------------------------------------------------------------------------------
