$(document).ready(function(e) 
{
	 function getParameterByName(name) {
		name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
		var regexS = "[\\?&]" + name + "=([^&#]*)";
		var regex = new RegExp(regexS);
		var results = regex.exec(window.location.search);
		if (results == null)
		return "";
		else
		return decodeURIComponent(results[1].replace(/\+/g, " "));
	}
	
	

	var searchKeys = new Array();
	var searchVals = new Array();
	
	searchKeys = 
	[
		'ZN Kod Çatısı İndir',
		'Kurulum Talimatları',
		'Dizin ve Dosya Yapısı',
		'Sorun Giderme',	
	
		'Bazı Kavramların Anlamları',
		'Çalışma Mantığını Anlamak',
		'Sayfa Çağırma',
		'Basit Bir Uygulama Yapmak',
		'URL Düzenleme',
		'Sınıfların Dahil Edilmesi',
		'Araçların Dahil Edilmesi',
		'Otomatik Dahil Etme',
			
		'ZN URL Yapıları',
		'Controllers Sayfa Yönetimi',
		'Pages Sayfa Tasarımı',
		'Model Kullanımı',
		'Tanımlı Sabitler ve Fonksiyonlar',
		'Çekirdek Sınıflar Import ve Config',	
			'Pages Sayfa Tasarımı Dahil Etmek',
			'Model Dosyasını Dahil Etmek',
			'Kütüphane(Library) Dahil Etmek',
			'Araç(Tool) Dahil Etmek',
			'Dil(Language) Dahil Etmek',
			'Script Dosyası Dahil Etmek',
			'Css Stil Dosyası Dahil Etmek',
			'Font Dosyası Dahil Etmek',
			'Herhangi Bir Dosya Dahil Etmek',
			'Paket Dosyaları Dahil Etmek',	
			'Herhangi Bir Ayarın Değerini Almak',
			'Herhangi Bir Ayarın Değerini Değiştirmek',	
		'Kütüphane ve Araç Oluşturma',
		'Dil(Lang) Metodu',	
		
		'Nesne Erişim Yöntemleri',
			'Dinamik Erişim($this->class->func())',
			'Statik Erişim(class::func())',
			'Değişkensel Erişim(Çağrı) (zn::$use->class->func())',
			'Yöntemsel Erişim(Çağrı) (this()->class->func())',
		
		'Kullanılabilir Fonksiyonlar',
			'Değişkenlerin Tanımlanmama Durumunu Kontrol Etmek » undefined()',
			'Değişkenlerin Tanımlanma Durumunu Kontrol Etmek » is_defined()',
			'Bir Dosyanın Dahil Edilme Durumunu Kontrol Etmek » is_import()',
			'Bir Dosyanın Var Olma Durmunu Kontrol Etmek » is_file_exists()',
			'Bir Dizinin Var Olma Durmunu Kontrol Etmek » is_dir_exists()',
			'Bir Verinin URL Yapısına Uygunluğunu Kontrol Etmek » is_url()',
			'Bir Verinin E-posta Adresine Uygunluğunu Kontrol Etmek » is_email()',
			'Bir Verinin Metinsel, Numerik veya Boolean Türe Uygunluğunu Kontrol Etmek » is_value()',
			'Bir Verinin Metinsel veya Numerik Türe Uygunluğunu Kontrol Etmek » is_char()',
			'Sitenin Dil İçeriğini Ayarlamak » set_lang()',
			'Sitenin Aktif Dil İçeriğini Öğrenmek » get_lang() , current_lang()',
			'Bir Veriye Önek Eklemek » prefix()',
			'Bir Veriye Sonek Eklemek » suffix()',
			'Sayfanın Aktif URL Adresini Öğrenmek » current_url()',
			'Sitenin URL Adresini Öğrenmek » site_url()',
			'Sitenin URL Adresini Öğrenmek » site_url()',
			'Gelinen Bir Önceki URL Adresini Öğrenmek » prev_url()',
			'Host URL Adresini Öğrenmek » hostname()',
			'Sitenin Aktif Yolunu Öğrenmek » current_path()',
			'Sitenin Kök Yolunu Öğrenmek » base_path()',
			'Gelinen Bir Önceki Yolu Öğrenmek » prev_path()',
			'URL Ekli Yolu Ham Yola Çevirmek » file_path()',
			'Yol Bilgilerine Ulaşmak » path_info()',
			'Dosya Uzantılarını Öğrenmek » extension()',
			'Dosya Uzantılarını Kaldırmak » remove_extension()',
			'Metinsel İfadeyi Bölmek ve İstenen Parçaya Ulaşmak » divide()',
			'Ip Numarasını Öğrenmek » ipv4()',
			'Server Verilerine Erişmek » server()',
			'Yönlendirme Yapmak » redirect()',
			'Yönlendirmeden Gelen Veriyi Kullanmak » redirect_data()',
			'Hızlı Kütüphane ve Yöntemlerini Kullanmak » library()',
			'Hızlı Araç ve Yöntemlerini Kullanmak » tool()',
			'Dahil Edilen Kütüphaneleri Öğrenmek » imported_libraries()',
			'Dahil Edilen Araçları Öğrenmek » imported_tools()',		
		'Sistem İçin Gerekli Fonksiyonlar',
			'Aktif URI Yolunu Öğrenmek » current_uri()',
			'Enjeksiyon Saldırılarını Önlemek » clean_injection()',
			'Kütüphanelerin ve Araçların Kullanımından Kaynaklı Hataları Raporlamak » report()',
			'Htaccess Ayar Dosyası Oluşturmak » create_htaccess_file()',
			'Otomatik Olarak Dahil Etmek » autoload()',
			'Başlık Bilgileri Oluşturmak » headers()',
			'SSL ve index.php Durumunu Öğrenmek » ssl_status() , index_status()',	
					
		'Dahil Etme Yöntemleri',
		'Masterpage Kullanımı',
			'Herhangi Bir Sayfayı Masterpage\'e Dönüştürmek',
			'Masterpage Olarak Belirlenen Sayfaya Veri Göndermek',
			'Masterpage\'e Başlık Bilgileri Göndermek',
			'Masterpage Konfigürasyon Dosyasını Kullanarak Başlık Bilgileri Göndermek',		
			
		'Database Ayarlarını Yapılandırma',
			'Veritabanı Ayarları',
			'Veritabanı Sürücüleri',
			'Cubrid Sürücü Ayarları',
			'Fbsql Sürücü Ayarları',
			'Ibase Sürücü Ayarları',
			'Mssql Sürücü Ayarları',
			'Mysql Sürücü Ayarları',
			'Mysqli Sürücü Ayarları',
			'Oci8 Sürücü Ayarları',
			'Odbc Sürücü Ayarları',
			'Postgre Sürücü Ayarları',
			'Sqlite Sürücü Ayarları',
			'Sqlite3 Sürücü Ayarları',
			'Sqlsrv Sürücü Ayarları',
			'Sybase Sürücü Ayarları',
			'PDO Veritabanı Sürücü Ayarları',
			'PDO 4d Sürücü Ayarları',
			'PDO Cubrid Sürücü Ayarları',
			'PDO Dblib Sürücü Ayarları',
			'PDO Firebird Sürücü Ayarları',
			'PDO Ibm Sürücü Ayarları',
			'PDO Informix Sürücü Ayarları',
			'PDO Mysql Sürücü Ayarları',
			'PDO Oci Sürücü Ayarları',
			'PDO Odbc Sürücü Ayarları',
			'PDO Pgsql Sürücü Ayarları',
			'PDO Sqlite Sürücü Ayarları',
			'PDO Sqlsrv Sürücü Ayarları',
		'Database(Db) Sınıfı',
			'Database Kütüphanesini Dahil Etmek',
			'Hızlı Başlangıç ve Kullanım Örnekleri',
			'Standart Sorgu Oluşturmak » $this->db->query()',
			'Tek Seferlik Çalıştırılabilir Sorgu Oluşturmak » $this->db->exec_query()',
			'Veritabanından Veri Çekmek » $this->db->get()',
			'Sorgu Sonucu Verilerini Kullanmak',
			'Select, From ve Where Deyimlerini Kullanmak',
			'Veritabanına Veri Eklemek » $this->db->insert()',
			'Veritabanında Veri Güncellemek » $this->db->update()',
			'Veritabanından Veri Silmek » $this->db->delete()',
			'Veri Güvenliğini Sağlamak » $this->db->secure()',
			'Diğer Veritabanı Yöntemleri',
		'Transaction Sorgu Oluşturmak',
			'Transaction Sorgusunu Başlatmak » $this->db->trans_start()',
			'Transaction Sorgusunu Bitirmek » $this->db->trans_end()',
			'Transaction Sorgulara Örnekler',
		'Database Oluşturma(DbForge) Sınıfı',
			'Database Forge Kütüphanesini Dahil Etmek',
			'Veritabanı Oluşturmak » $this->db->create_database()',
			'Veritabanını Silmek » $this->db->drop_database()',
			'Tablo Oluşturmak » $this->db->create_table()',
			'Tablo Silmek » $this->db->drop_table()',
			'Tabloyu Düzenlemek » $this->db->alter_table()',
			'Tablo İsmini Değiştirmek » $this->db->rename_table()',
			'Tabloya Sütun Eklemek » $this->db->add_column()',
			'Tablodan Sütun Silmek » $this->db->drop_column()',
			'Sütun İsmini Değiştirmek » $this->db->rename_column()',
			'Sütün Bilgilerini Düzenlemek » $this->db->modify_column()',
			'Tablo Verilerini Boşaltmak » $this->db->truncate()',
		'Database Araç(DbTool) Sınıfı',
			'Database Tool Kütüphanesini Dahil Etmek',
			'Oluşturulan Veritabanlarının Listesini Almak » $this->db->list_databases()',
			'Veritabanında Oluşturalan Tabloların Listesini Almak » $this->db->list_tables()',
			'Veritabanının Yedeğini Almak » $this->db->backup()',
			'Tabloları Uygun Hale Getirmek » $this->db->optimize_tables()',
			'Tabloları Onarmak » $this->db->repair_tables()',
		'Farklı Veritabanı Bağlantısı Oluşturmak',
			'Database Ayarlarını Yapılandırmak',
			'Farklı Bir Veritabanı Bağlantısı Oluşturmak » $this->xxx->different_connection()',
		'Statik Formda Veritabanı Kullanımı',
			'Statik Formda Database Kütüphanesini Dahil Etmek',
			'Statik Formda Örnek Kullanımlar',
		
		'Ajax Sınıfı',
			'Ajax Kütüphanesini Dahil Etmek',
			'Ajax ile Veri Göndermek » ajax::send()',
			'JSON Tipinde Veri Döndürmek » ajax::json_send_back()',
			'Veri Döndürmek » ajax::send_back()',
			'Gelen Verileri Kontrol Etmek » ajax::pr()',
			'Gelen Verileri Değer Kontrol Etmek » ajax::dump()',
			'Ajax Yöntemiyle Sayfalama Yapmak » ajax::pagination()',
		'Benchmark Sınıfı',
			'Benchmark Kütüphanesini Dahil Etmek',
			'Benchmark Testini Başlatmak » bench::test_start()',
			'Benchmark Testini Bitirmek » bench::test_end()',
			'Test Esnasında Geçen Süreyi Öğrenmek » bench::elapsed_time()',
			'PHP Betiğinin Kullandığı Bellek Miktarını Öğrenmek » bench::memory_usage()',
			'PHP Betiğine Ayrılan Maksimum Bellek Miktarını Öğrenmek » bench::max_memory_usage()',
			'Bir PHP Betiğinin Kullandığı Bellek Miktarını Hesaplamak » bench::calculated_memory()',
		'Cart Sınıfı',
			'Cart Kütüphanesini Dahil Etmek',
			'Sepete Eklemek » cart::insert_item()',
			'Sepetteki Ürünü Seçmek » cart::select_item()',
			'Sepetteki Verileri Öğrenmek » cart::select_items()',
			'Sepetteki Ürünlerin Toplam Fiyatını Öğrenmek » cart::total_prices()',
			'Sepetteki Toplam Ürünü Öğrenmek » cart::total_items()',
			'Sepetteki Verileri Güncellemek » cart::update_item()',
			'Sepetteki Veriyi Silmek » cart::delete_item()',
			'Sepetteki Tüm Veriyi Silmek » cart::delete_items()',
			'Para Biçimine Çevirmek » cart::money_format()',
			'Sepet Sınıfı Kullanımı Esnasında Hata Tespiti Yapmak » cart::error()',
		'Cookie Sınıfı',
			'Cookie Kütüphanesini Dahil Etmek',
			'Çerez Oluşturmak » cook::insert()',
			'Oluşturulan Çerezi Seçmek » cook::select()',
			'Çerez Silmek » cook::delete()',
			'Tüm Çerezleri Seçmek » cook::select_all()',
			'Tüm Çerezleri Silmek » cook::delete_all()',
			'Çerezlerin Kullanımı Esnasında Hata Tespiti Yapmak » cook::error()',
		'Css3 Sınıfı',
			'Css3 Kütüphanesini Dahil Etmek',
			'Style Tagı Açmak » css3::open()',
			'Style Tagı Kapatmak » ss3::close()',
			'Dönüşüm Stilleri Eklemek » css3::transform()',
			'Geçiş Efektleri Uygulamak » css3::transition()',
			'Gölge Efekti Uygulamak » css3::box_shadow()',
			'Köşeleri Yumuşatmak » css3::border_radius()',
			'Herhangi Bir CSS3 Stili Kullanmak » css3::code()',
		'Curl Sınıfı',
			'Curl Kütüphanesini Dahil Etmek',
			'CURL Uygulamasını Başlatmak » curl::open()',
			'CURLOPT_XXX Seçenekleri Eklemek » curl::settings()',
			'CURL Uygulamasını Çalıştırmak » curl::execute()',
			'CURL Uygulamasını Kapatmak » curl::close()',
			'CURL Uygulaması Hakkında CURLINFO_XXX Bilgisi Almak » curl::info()',
			'CURL Uygulaması Esnasında Hata Kontrolü Yapmak » curl::error()',
			'Hata Numarasını Öğrenmek » curl::errno()',
			'Hatanın Ne Olduğunu Öğrenmek » curl::errval()',
			'CURL Versiyonunu Öğrenmek » curl::version()',
		'Download Sınıfı',
			'Download Kütüphanesini Dahil Etmek',
			'Dosya İndirme download::start();',
		'Email Sınıfı',
			'Email Kütüphanesini Dahil Etmek',
			'Harici Genel E-posta Ayarlarını Yapılandırmak » Config/Email.php',
			'Dahili E-posta Ayarlarını Yapılandırmak » email::settings()',
			'E-posta Kullanımını Başlatmak » email::open()',
			'E-posta Kullanımını Sonlandırmak » email::close()',
			'E-posta Alıcısı Eklemek » email::receiver()',
			'E-posta Göndericisi Eklemek » email::sender()',
			'E-posta Konusu Oluşturmak » email::subject()',
			'E-posta İçeriği Oluşturmak » email::message()',
			'E-posta\'yı Göndermek » email::send()',
			'E-posta İçeriğine Dosya Eklemek » email::add_attachment()',
			'E-posta İşlemleri Sırasında Hata Bilgisi Almak » email::error()',
			'E-posta Hakkında Detaylı Bilgi Almak » email::detail()',
			'E-posta Sınıfının Diğer Yöntemleri',
		'Encode Sınıfı',
			'Encode Kütüphanesini Dahil Etmek',
			'Şifre Oluşturmak » encode::create()',
			'Altın Şifreleme Yapmak » encode::golden()',
			'Süper Şifreleme Yapmak » encode::super()',
			'Farklı Türlerde Şifleme Yapmak » encode::type()',
		'File Sınıfı',
			'File Kütüphanesini Dahil Etmek',
			'Dosya Okumak » file::read()',
			'Dosyaya Veri Yazmak » file::write()',
			'Dosyaya Veri Yazmak » file::append()',
			'Dosya Oluşturmak »file::create()',
			'Dosya Silmek »file::delete()',
			'Dosya İçeriğini Almak » file::contents()',
			'Dosya İçinde Arama Yapmak » file::find()',
			'Dosya İzinlerini Yönetmek » file::permission()',
			'Dosyanın Oluşturulma Tarihini Öğrenmek » file::create_date()',
			'Dosyanın Değiştirilme Tarihini Öğrenmek » file::change_date()',
			'Dosyanın Boyutunu Öğrenmek » file::size()',
			'Zip Dosyasını Çıkartmak » file::zip_extract()',
		'Folder Sınıfı',
			'Folder Kütüphanesini Dahil Etmek',
			'Dizin Oluşturmak » folder::create()',
			'Boş Dizini Silmek » folder::delete_empty()',
			'Tüm Dizini Silmek » db::delete()',
			'Tüm Dizini Kopyalamak » folder::copy()',
			'Dizin İçindeki İstenilen Dosya ve Dizinleri Öğrenmek » folder::files()',
			'Dizin İçindeki Tüm Dosya ve Dizinleri Öğrenmek » folder::all_files()',
			'Dosya Yetkilerini Düzenlemek » folder::permission()',
		'Form Sınıfı',
			'Form Kütüphanesini Dahil Etmek',
			'Form Açmak » form::open()',
			'Form Kapatmak » form::close()',
			'Yazı Kutusu Oluşturmak » form::text()',
			'Şifre Text Kutusu Oluşturmak » form::password()',
			'Yazı Alanı Kutusu Oluşturmak » form::textarea()',
			'Submit Butonu Oluşturmak » form::submit()',
			'Temizleme Butonu Oluşturmak » form::reset()',
			'Buton Oluşturmak » form::button()',
			'Radyo Butonu Oluşturmak » form::radio()',
			'Çek Butonu Oluşturmak » form::checkbox()',
			'Seçim Listesi Oluşturmak » form::select()',
			'Çoklu Seçim Listesi Oluşturmak » form::multiple()',
			'Dosya Butonu Oluşturmak » form::file()',
		'FTP Sınıfı',
			'FTP Kütüphanesini Dahil Etmek',
			'FTP Bağlantısı Oluşturmak » ftp::connect()',
			'Dizin Oluşturmak » ftp::create_folder()',
			'Dizini Silmek » ftp::delete_folder()',
			'Çalışma Dizinini Değiştirmek » ftp::change_folder()',
			'Dosya ve Dizin Adını Değiştirmek » ftp::rename()',
			'Dosya Silmek » ftp::delete_file()',
			'Dosya Boyutunu Öğrenmek » ftp::file_size()',
			'Sunucudan Dosya İndirmek » ftp::download()',
			'Sunucuya Dosya Yüklemek » ftp::upload()',
			'Bir Dizin İçindeki Dosya ve Dizin Listesini Öğrenmek » ftp::files()',
			'Dosya ve Dizin Yetkilerini Düzenlemek » ftp::permission()',
		'Html5 Sınıfı',
			'HTML5 Kütüphanesini Dahil Etmek',
			'Form Açmak » html5::form_open()',
			'Form Kapatmak » html5::form_close()',
			'E-posta Nesnesi Oluşturmak » html5::email_object()',
			'URL Nesnesi Oluşturmak » html5::url_object()',
			'Sayı Kontrol Nesnesi Oluşturmak » html5::number_object()',
			'Arama Nesnesi Oluşturmak » html5::search_object()',
			'Telefon Kontrol Nesnesi Oluşturmak » html5::tel_object()',
			'Renk Nesnesi Oluşturmak » html5::color_object()',
			'Tarih Nesnesi Oluşturmak » html5::date_object()',
			'Tarih/Saat Nesnesi Oluşturmak » html5::datetime_object()',
			'Yerel Tarih/Saat Nesnesi Oluşturmak » html5::datetime_local_object()',
			'Saat Nesnesi Oluşturmak » html5::time_object()',
			'Hafta Bilgi Nesnesi Oluşturmak » html5::week_object()',
			'Ay Bilgi Nesnesi Oluşturmak » html5::month_object()',
			'Aralık Belirleme Nesnesi Oluşturmak » html5::range_object()',
			'Imaj Nesnesi Oluşturmak » html5::image_object()',
			'Herhangi Bir Input Nesnesi Oluşturmak » html5::input_object()',
			'Üst Bilgi İçeriği Oluşturmak » html5::header()',
			'Alt Bilgi İçeriği Oluşturmak » html5::footer()',
			'İç ve Dış Bağlantıları Gruplandırmak » html5::nav()',
			'Makale Bilgi İçeriği Oluşturmak » html5::article()',
			'Reklam Bilgi İçeriği Oluşturmak » html5::aside()',
			'Komut Düğmeleri Tanımlamak » html5::command()',
			'Detaylar Nesnesi Oluşturmak » html5::details()',
			'Özet Bilgi Nesnesi Oluşturmak » html5::summary()',
			'Görsel Nesneleri Gruplandırmak » html5::figure()',
			'Görsel Nesnelere Başlık Bilgisi Oluşturmak » html5::figcaption()',
			'Başlık Nesnelerini Gruplamak » html5::hgroup()',
			'İçeriğin Önemli Yerlerini Belirtmek » html5::mark()',
			'Maksimum ve Minimum Değerler Belirtmek » html5::meter()',
			'İşlem Devam Ediyor Bildirimi Almak » html5::progress()',
			'Bir Web Sayfasının Bölümlerini Tanımlamak » html5::section()',
			'Tarih ve Saat Bilgisi Oluşturmak » html5::time()',
			'Sohbet Nesnesi Oluşturmak » html5::dialog()',
			'Farklı Türlerde Çıkış Almak » html5::output()',
			'Çizim Nesnesi Oluşturmak » html5::canvas()',
			'Formun Giriş Değerleri İçin Seçenek Listesi Oluşturmak » html5::datalist()',
			'Ses Öğelerini Kullanmak » html5::audio()',
			'Vidyo Öğelerini Kullanmak » html5::video()',
			'Ses ve Vidyo Öğelerinin Kaynağını Belirtmek » html5::source()',
			'Ses ve Vidyo Öğelerini Dış Kaynaklardan Çekmek » html5::embed()',
			'Şifre Üretmek » html5::keygen()',
		'Image Sınıfı',
			'Image Kütüphanesini Dahil Etmek',
			'Resmi Boyutlandırmak » image::thumb()',
			'Resmin Orantılı Genişlik Yükseklik Değerini Almak » image::size()',
		'Jquery Sınıfı',
			'Jquery Kütüphanesini Dahil Etmek',
			'Script Tagı Açmak » jquery::open()',
			'Script Tagı Kapatmak » jquery::close()',
			'Document Ready Yapısını Kullanmak » jquery::ready()',
			'Olay Dinleyicisi Eklemek » jquery::event()',
			'Fade In, Fade Out Animasyonu Kullanmak » jquery::fade()',
			'Slide Up, Slide Down Animasyonu Kullanmak » jquery::slide()',
			'Toggle Yapısı Kullanmak » jquery::toggle()',
			'Hide Yapısı Kullanmak » jquery::hide()',
			'Show Yapısı Kullanmak » jquery::show()',
			'Animage Animasyon Yapıcısı Kullanmak » jquery::animate()',
			'Ajax Yapısı Kullanmak » jquery::ajax()',
			'CSS Stil Ekleyicisi Kullanmak » jquery::css()',
			'Attr Özellik Ekleyicisi Kullanmak » jquery::attr()',
			'Fonksiyon Eklemek » jquery::func()',
			'Herhangi Bir Kod Kullanmak » jquery::code()',
		'Json Sınıfı',
			'Json Kütüphanesini Dahil Etmek',
			'Dizi Verilerini Özel Veri Türüne Çevirmek » json::encode()',
			'Özel Verileri Object Dizi Verilerine Çevirmek » json::decode()',
		'Method Sınıfı',
			'Method Kütüphanesini Dahil Etmek',
			'POST Verilerini Verileri Kullanmak » method::post()',
			'GET Verilerini Kullanmak » method::files()',
			'REQUEST Verilerini Kullanmak » method::request()',
			'FILES Verilerini Kullanmak » method::files()',
		'Pagination Sınıfı',
			'Pagination Kütüphanesini Dahil Etmek',
			'Sayfalama Ayarlarını Yapmak » pag::settings()',
			'Sayfalamayı Oluşturmak » pag::create()',
		'Permission Sınıfı',
			'Permission Kütüphanesini Dahil Etmek',
			'Nesne Erişim Yetkilerini Düzenlemek » perm::process()',
			'Sayfa Erişim Yetkilerini Düzenlemek » pag::page()',
		'Regex Sınıfı',
			'Regex Kütüphanesini Dahil Etmek',
			'Metinsel Veriler İçinde Eşleşme Sağlamak » reg::match() , reg::match_all()',
			'Eşleşen Veriler Değiştirmek » reg::replace()',
		'Search Sınıfı',
			'Search Kütüphanesini Dahil Etmek',
			'Site İçi Arama Yapmak ve Arama Sonuçlarını Almak » search::get()',
			'Arama Sonuçlarına Filtre Uygulamak » search::filter() ve search::or_filter()',
		'Security Sınıfı',
			'Security Kütüphanesini Dahil Etmek',
			'Kötü Amaçlı Kodları Değiştirmek » sec::nc_encode()',
			'Kötü Amaçlı Çapraz Kodları Dönüştürmek » sec::xss_encode()',
			'Tırnak Enjeksiyonları Dönüştürmek ve Eski Haline Getirmek » sec::injection_encode() , sec::html::injection_decode()',
			'Html Karakterlerini Dönüştürmek ve Eski Haline Getirmek » sec::html_encode() , sec::html::decode()',
		'Session Sınıfı',
			'Session Kütüphanesini Dahil Etmek',
			'Oturum Verisi Oluşturmak » sess::insert()',
			'Oluşturulan Oturumları Seçmek » sess::select()',
			'Tüm Oturumları Seçmek » sess::select_all()',
			'Oluşturulan Oturumu Silmek » sess::delete()',
			'Tüm Oturumları Silmek » sess::delete_all()',
		'Upload Sınıfı',
			'Upload Kütüphanesini Dahil Etmek',
			'Dosya Yükleme Ayarlarını Yapılandırmak » upload::settings()',
			'Dosya Yükleme İşlemini Başlatmak » upload::start()',
			'Dosya Yükleme İşlemleri Hakkında Bilgi Almak » upload::info()',
			'Dosya Yükleme İşlemleri Sırasında Ortaya Çıkan Hataları Öğrenmek » upload::error()',
		'Uri Sınıfı',
			'Uri Kütüphanesini Dahil Etmek',
			'İstenilen URI Bölümüne Bölüm Adı İle Ulaşmak » uri::get()',
			'İstenilen URI Bölümüne Indeks Numarası İle Ulaşmak » uri::segment()',
			'Uri\'nin Bölümlerini Dizi Olarak Almak » uri::segment_array()',
			'Toplam Bölüm Sayısını Öğrenmek » uri::total_segments()',
		'User Sınıfı',
			'User Kütüphanesini Dahil Etmek',
			'User Sınıfını Veritabanıyla İlişkilendirmek ve Konfigürasyon Dosyasını Yapılandırmak',
			'Siteye Kayıt Olmak » user::register()',
			'Siteye Giriş Yapmak » urer::login()',
			'Üyelik Bilgilerini Güncellemek » user::update()',
			'Üyelik Oturumunu Kapatmak » user::logout()',
			'Üye Girişinin Yapılıp Yapılmadığını Kontrol Etmek » user::is_login()',
			'Oturum Açan Üyenin Bilgilerine Ulaşmak » user::data()',
			'Şifremi Unuttum Sistemi Oluşturmak » user::forgot_password()',
			'Aktivasyon İşlemini Tamamlamak » user::activation_complete()',
			'Üye İşlemleri Esnasında Oluşan Hataları Öğrenmek » user::error()',
			'Üye İşlemlerinin Başarı İle Tamamlandığı Bilgisini Almak » user::success()',
		'Validation Sınıfı',
			'Validation Kütüphanesini Dahil Etmek',
			'Validasyon Kontrol Parametreleri',
			'Validasyon Kontrol Kuralları Oluşturmak » val::rules()',
			'Kontrolleri Sağlanmış Veriyi Kullanmak » val::nval()',
			'Validasyon Kontrol Kurallarına Uymayan Verilerin Hata Bilgisini Almak » val::error()',
			'Post Edilen Sayfa Sonrası Form Değerlerini Korumak » val::post_back()',		
		'Xml Sınıfı',	
			'Xml Kütüphanesini Dahil Etmek',
			'XML Verisi Oluşturmak » xml::create()',
			'Element Eklemek » xml::add_element()',
			'Element Silmek » xml::remove_element()',
			'Elemente Özellik Eklemek » xml::add_attr()',
			'Elementin Özelliğini Kaldırmak » xml::remove_attr()',
			'Özelliğin Değerine Ulaşmak » xml::get_attr()',
			'Elemente İçerik Eklemek » xml::add_content()',
			'Elementin Değerine Ulaşmak » xml::get_content()',
			'Elementin İsmine Göre İçeriği Dizi Olarak Almak » xml::get_contents_by_name()',
			'Elementin Id\'sine Göre İçeriği Almak » xml::get_content_by_id()',
			'XML Versini Kaydetmek » xml::save()',
			'Harici XML Dosyası Veya XML Metni Yüklemek » xml::load()',
			'Yüklenmiş Harici XML Dosyasının Element ve Değerlerine Ulaşmak » xml::path()',
			
		'Ajax Aracı',
			'Ajax Aracını Dahil Etmek',
			'JSON Tipinde Veri Döndürmek » json_send_back()',
			'Standart Veri Döndürmek » send_back()',
		'Array Aracı',
			'Array Aracını Dahil Etmek',
			'Bir Dizi Elemanının Yerini Değiştirmek » array_pos_change()',
			'Bir Dizide Elemanları Birbiri İle Yer Değiştirmek » array_pos_reverse()',
			'Diziden Eleman Silmek » array_delete_element()',
			'Bir Değere Birden Fazla Anahtar İfade Eklemek » multi_key_array()',
			'Dizinin Anahtar veya Değer Bilgisine Ulaşmak » array_keyval()',
			'Diziyi Object Veri Türüne Çevirmek » array_object()',
		'Builder Aracı',
			'Builder Aracını Dahil Etmek',
			'Xml Yapıcısı » xml_builder()',
			'Liste Yapıcısı » list_builder()',
			'Table Yapıcısı » table_builder()',
		'Captcha Aracı',
			'Captcha Aracını Dahil Etmek',
			'Güvenlik Kodu Oluşturmak » create_captcha()',
			'Güvenlik Kodunu Öğrenmek » get_captcha_code()',
		'Cleaner Aracı',
			'Cleaner Aracını Dahil Etmek',
			'Temizleme Aracı » cleaner()',
		'Converter Aracı',
			'Converter Aracını Dahil Etmek',
			'Karakter Dönüştürücü » char_converter()',
			'Aksan Dönüştürücü » accent_converter()',
			'URL\'ye Uygun Kelime Dönüştürücü » url_word_converter()',
			'Büyük Küçük Harf Dönüştürücü » case_converter()',
			'Karakter Seti Dönüştürücü » charset_converter()',
		'Creator Aracı',
		 	'Creator Aracını Dahil Etmek',
			'Şifre Oluşturma Aracı » password_creator()',
		'DateTime Aracı',
			'DateTime Aracını Dahil Etmek',
			'Standart Zaman Aracı » standart_time()',
			'Şimdiki Saat Aracı » current_time()',
			'Şimdiki Tarih Aracı » current_date()',
			'Şimdiki Tarih ve Zaman Aracı » current_date_time()',
			'Tarih ve Saat Ayarlama Aracı » set_time()',
			'Tarih ve Saat Ayarlama Aracı » set_date()',
		'Email Aracı',
			'Email Aracını Dahil Etmek',
			'E-posta Gönderme Aracı » send_email()',
			'Imap E-posta Gönderme Aracı » send_imap_email()',
		'Encoder Aracı',
			'Encoder Aracını Dahil Etmek',
			'Şifreleme Aracı » encoder()',
			'Php Taglarını Şifreleme Aracı » php_tag_encoder()',
			'Tırnak İşaretlerini Şifreleme Aracı » nail_encoder()',
			'Yabancı Karakterleri Şifreleme Aracı » foreign_char_encoder()',
		'Filter Aracı',
			'Filter Aracını Dahil Etmek',
			'Kelime Filtreleme Aracı » word_filter()',
		'Formatter Aracı',
			'Formatter Aracını Dahil Etmek',
			'Byte Biçimlendirme Aracı » byte_formatter()',
			'Para Biçimlendirme Aracı » money_formatter()',
			'Zaman Biçimlendirme Aracı » time_formatter()',
		'Html Aracı',
			'Html Aracını Dahil Etmek',
			'Eleman Aracı » html_element()',
			'Çoklu Özellik Ekleme Aracı » multi_attr()',
			'Başlık Aracı » heading()',
			'Yazı Biçimlendirme Aracı » font()',
			'Paragraf Aracı » parag()',
			'Koyu Yazı Aracı » bold()',
			'Koyu Yazı Aracı » strong()',
			'Eğik Yazı Aracı » italic()',
			'Altı Çizgili Yazı Aracı » underline()',
			'Üstü Çizgili Yazı Aracı » overline()',
			'Alt Yazı Aracı » undertext()',
			'Üst Yazı Aracı » overtext()',
			'Köprü Aracı » anchor()',
			'Mail Köprü Aracı » mailto()',
			'Resim Aracı » image()',
			'Boşluk Bırakma Aracı » space()',
			'Bir Alt Satıra Geçirme Aracı » br()',
			'Meta Etiketi Aracı » meta()',
		'Limiter Aracı',
			'Limiter Aracını Dahil Etmek',
			'Kelime Sınırlama Aracı » word_limiter()',
			'Karakter Sınırlama Aracı » char_limiter()',
		'Parser Aracı',
			'Parser Aracını Dahil Etmek',
			'Tür Dönüştürme Aracı » parser()',
		'Reader Aracı',
			'Reader Aracını Dahil Etmek',
			'Rss Okuma Aracı » rss_reader()',
		'Repeater Aracı',
			'Repeater Aracını Dahil Etmek',
			'Tekrarlama Aracı » repeater()',
		'Rounder Aracı',
			'Rounder Aracını Dahil Etmek',
			'Yuvarlama Aracı » rounder()',
		'Searcher Aracı',
			'Searcher Aracını Dahil Etmek',
			'Dizi ve Metinlerde Arama Aracı » searcher()',
		'Sound Aracı',
			'Sound Aracını Dahil Etmek',
			'Ses Dosyası Ekleme Aracı » add_sound()',
		'String Aracı',
			'String Aracını Dahil Etmek',
			'Metindeki Tüm Boşlukları(Baştaki, Sondaki ve Ortadaki) Temizleme Aracı » mtrim()',
			'Taksim (/) İşaretini Temizleme Aracı » trim_slashes()',
			'Büyük Harfe Çevirme Aracı » uppercase()',
			'Küçük Harfe Çevirme Aracı » lowercase()',
			'Sadece İlk Harfi Büyük Harfe Çevirme Aracı » titlecase()',
			'Metinsel İfadeleri Kırpma Aracı » substring()',
			'Metinsel İfadelerde Arama Aracı » string_search()',
			'Metinsel İfadelerde Karakterler Arası Yer Değiştirme Aracı » string_reshuffle()',
			'Metinsel İfadelerde Tekrarlanayan Metin Sayısını Hesaplama Aracı » string_recurrent_count()',
			'Metinsel İfadelerde Karakter Yerleştirme Aracı » string_placement()',
		'Symbol Aracı',
			'Symbol Aracını Dahil Etmek',
			'Sembol Aracı » symbol()',
		'Uploader Aracı',
			'Uploader Aracını Dahil Etmek',
			'SQL Dosyasını Yükleme Aracı » sql_file_uploader()',
			'Dosya Yükleme Aracı » file_uploader()',
				
		'Config Sınıfı ve Kullanımı',
		'Autoload Ayarları',
		'Cache Ayarları',
		'Captcha Ayarları',
		'Cookie Ayarları',
		'Curl Ayarları',
		'Database Ayarları',
		'DateTime Ayarları',
		'Doctype Ayarları',
		'Email Ayarları',
		'Encode Ayarları',
		'ForeignChars Ayarları',
		'Log Ayarları',
		'Headers Ayarları',
		'Htaccess Ayarları',
		'Ini Ayarları',
		'Language Ayarları',
		'Masterpage Ayarları',
		'Permission Ayarları',
		'Regex Ayarları',
		'Repair Ayarları',
		'Route Ayarları',
		'Security Ayarları',
		'Session Ayarları',
		'Symbols Ayarları',
		'Upload Ayarları',
		'Uri Ayarları',
		'User Ayarları',
	];
	
	searchVals = 
	[
		'download',
		'installation',
		'directory_structure',
		'troubleshooting',
			
		'concepts',
		'operation_logic',
		'import_page',
		'basic_app',
		'url_edit',
		'import_library',
		'import_helper',
		'autoload',
				
		'zn_url',
		'management',
		'pages',
		'model',
		'reserved_functions',
		'core_libraries',
			'core_libraries.html#import_page',
			'core_libraries.html#import_management',
			'core_libraries.html#import_library',
			'core_libraries.html#import_helper',
			'core_libraries.html#import_language',
			'core_libraries.html#import_script',
			'core_libraries.html#import_style',
			'core_libraries.html#import_font',
			'core_libraries.html#import_something',
			'core_libraries.html#import_package',
			'core_libraries.html#config_get',
			'core_libraries.html#config_set',	
		'create_library',
		'lang',	
		
		'access_methods',
			'access_dynamic',
			'access_static',
			'access_znuse',
			'access_this',
		
		'user_functions',
			'user_functions.html#undefined',
			'user_functions.html#is_defined',
			'user_functions.html#is_import',
			'user_functions.html#is_file_exists',
			'user_functions.html#is_dir_exists',
			'user_functions.html#is_url',
			'user_functions.html#is_email',
			'user_functions.html#is_value',
			'user_functions.html#is_char',
			'user_functions.html#set_lang',
			'user_functions.html#get_lang',
			'user_functions.html#prefix',
			'user_functions.html#suffix',
			'user_functions.html#current_url',
			'user_functions.html#site_url',
			'user_functions.html#base_url',
			'user_functions.html#prev_url',
			'user_functions.html#hostname',
			'user_functions.html#current_path',
			'user_functions.html#base_path',
			'user_functions.html#prev_path',
			'user_functions.html#file_path',
			'user_functions.html#path_info',
			'user_functions.html#extension',
			'user_functions.html#remove_extension',
			'user_functions.html#divide',
			'user_functions.html#ipv4',
			'user_functions.html#server',
			'user_functions.html#redirect',
			'user_functions.html#redirect_data',
			'user_functions.html#library',
			'user_functions.html#tool',	
			'user_functions.html#imported_libraries',
			'user_functions.html#imported_tools',	
		'system_functions',
			'system_functions.html#current_uri',
			'system_functions.html#clean_injection',
			'system_functions.html#report',
			'system_functions.html#create_htaccess_file',
			'system_functions.html#autoload',
			'system_functions.html#headers',
			'system_functions.html#status',
				
		'import_functions',
		'import_masterpage',
			'import_masterpage.html#import_masterpage',
			'import_masterpage.html#import_masterpage_send_data',
			'import_masterpage.html#import_masterpage_send_head_data',
			'import_masterpage.html#import_masterpage_config',	
		
		'db_config',
			'db_config.html#db_config',
			'db_config.html#db_driver',
			'db_config.html#db_cubrid_config',
			'db_config.html#db_fbsql_config',
			'db_config.html#db_ibase_config',
			'db_config.html#db_mssql_config',
			'db_config.html#db_mysql_config',
			'db_config.html#db_mysqli_config',
			'db_config.html#db_oci8_config',
			'db_config.html#db_odbc_config',
			'db_config.html#db_postgre_config',
			'db_config.html#db_sqlite_config',
			'db_config.html#db_sqlite3_config',
			'db_config.html#db_sqlsrv_config',
			'db_config.html#db_sybase_config',
			'db_config.html#db_pdo_config',
			'db_config.html#db_pdo_4d_config',
			'db_config.html#db_pdo_cubrid_config',
			'db_config.html#db_pdo_dblib_config',
			'db_config.html#db_pdo_firebird_config',
			'db_config.html#db_pdo_ibm_config',
			'db_config.html#db_pdo_informix_config',
			'db_config.html#db_pdo_mysql_config',
			'db_config.html#db_pdo_oci_config',
			'db_config.html#db_pdo_odbc_config',
			'db_config.html#db_pdo_pgsql_config',
			'db_config.html#db_pdo_sqlite_config',
			'db_config.html#db_pdo_sqlsrv_config',
		'db_db',
			'db_db.html#db_import',
			'db_db.html#quick_start',
			'db_db.html#standart_query',
			'db_db.html#exec_query',
			'db_db.html#get',
			'db_db.html#result',
			'db_db.html#select_from',
			'db_db.html#insert',
			'db_db.html#update',
			'db_db.html#delete',
			'db_db.html#secure',
			'db_db.html#other',
		'db_trans',
			'db_trans.html#trans_start',
			'db_trans.html#trans_end',
			'db_trans.html#trans_example',
		'db_forge',
			'db_forge.html#db_import',
			'db_forge.html#db_create',
			'db_forge.html#db_drop',
			'db_forge.html#db_create_table',
			'db_forge.html#db_drop_table',
			'db_forge.html#db_alter_table',
			'db_forge.html#db_rename_table',
			'db_forge.html#db_add_column',
			'db_forge.html#db_drop_column',
			'db_forge.html#db_rename_column',
			'db_forge.html#db_modify_column',
			'db_forge.html#db_truncate',
		'db_tool',
			'db_tool.html#db_import',
			'db_tool.html#db_list_databases',
			'db_tool.html#db_list_tables',
			'db_tool.html#db_backup',
			'db_tool.html#db_optimize_tables',
			'db_tool.html#db_repair_tables',
		'db_different_connect',
			'db_different_connect.html#db_config',
			'db_different_connect.html#db_different_connect',
		'db_static',
			'db_static.html#db_import',
			'db_static.html#quick_start',
			
		'lib_ajax',
			'lib_ajax.html#ajax_import',
			'lib_ajax.html#ajax_send',
			'lib_ajax.html#ajax_json_send_back',
			'lib_ajax.html#ajax_send_back',
			'lib_ajax.html#ajax_dump',
			'lib_ajax.html#ajax_dump',
			'lib_ajax.html#ajax_pagination',
		'lib_bench',
			'lib_bench.html#bench_import',
			'lib_bench.html#bench_test_start',
			'lib_bench.html#bench_test_end',
			'lib_bench.html#bench_elapsed_time',
			'lib_bench.html#bench_memory_usage',
			'lib_bench.html#bench_max_memory_usage',
			'lib_bench.html#bench_calculated_memory',
		'lib_cart',
			'lib_cart.html#cart_import',
			'lib_cart.html#cart_insert',
			'lib_cart.html#cart_select',
			'lib_cart.html#cart_items',
			'lib_cart.html#cart_total_items',
			'lib_cart.html#cart_total_items',
			'lib_cart.html#cart_update',
			'lib_cart.html#cart_delete',
			'lib_cart.html#cart_delete',
			'lib_cart.html#cart_money_format',
			'lib_cart.html#cart_error',
		'lib_cookie',
			'lib_cookie.html#cookie_import',
			'lib_cookie.html#cookie_insert',
			'lib_cookie.html#cookie_select',
			'lib_cookie.html#cookie_delete',
			'lib_cookie.html#cookie_all_delete',
			'lib_cookie.html#cookie_all_delete',
			'lib_cookie.html#cookie_error',
		'lib_css3',
			'lib_css3.html#css3_import',
			'lib_css3.html#css3_open',
			'lib_css3.html#css3_open',
			'lib_css3.html#css3_transform',
			'lib_css3.html#css3_transition',
			'lib_css3.html#css3_box_shadow',
			'lib_css3.html#css3_border_radius',
			'lib_css3.html#css3_code',
		'lib_curl',
			'lib_curl.html#curl_import',
			'lib_curl.html#curl_open',
			'lib_curl.html#curl_settings',
			'lib_curl.html#curl_execute',
			'lib_curl.html#curl_close',
			'lib_curl.html#curl_info',
			'lib_curl.html#curl_error',
			'lib_curl.html#curl_error',
			'lib_curl.html#curl_error',
			'lib_curl.html#curl_version',
		'lib_download',
			'lib_download.html#download_import',
			'lib_download.html#download_start',
		'lib_email',
			'lib_email.html#email_import',
			'lib_email.html#email_out_settings',
			'lib_email.html#email_in_settings',
			'lib_email.html#email_open',
			'lib_email.html#email_close',
			'lib_email.html#email_receiver',
			'lib_email.html#email_sender',
			'lib_email.html#email_subject',
			'lib_email.html#email_message',
			'lib_email.html#email_send',
			'lib_email.html#email_add_attachment',
			'lib_email.html#email_detail',
			'lib_email.html#email_detail',
			'lib_email.html#email_other',
		'lib_encode',
			'lib_encode.html#encode_import',
			'lib_encode.html#encode_create',
			'lib_encode.html#encode_golden',
			'lib_encode.html#encode_super',
			'lib_encode.html#encode_type',
		'lib_file',
			'lib_file.html#file_import',
			'lib_file.html#file_read',
			'lib_file.html#file_write',
			'lib_file.html#file_append',
			'lib_file.html#file_create',
			'lib_file.html#file_delete',
			'lib_file.html#file_contents',
			'lib_file.html#file_find',
			'lib_file.html#file_permission',
			'lib_file.html#file_create_date',
			'lib_file.html#file_create_date',
			'lib_file.html#file_size',
			'lib_file.html#file_zip_extract',
		'lib_folder',
			'lib_folder.html#folder_import',
			'lib_folder.html#folder_create',
			'lib_folder.html#folder_delete_empty',
			'lib_folder.html#folder_delete',
			'lib_folder.html#folder_copy',
			'lib_folder.html#folder_files',
			'lib_folder.html#folder_all_files',
			'lib_folder.html#folder_permission',
		'lib_form',
			'lib_form.html#form_import',
			'lib_form.html#form_open',
			'lib_form.html#form_close',
			'lib_form.html#form_text',
			'lib_form.html#form_password',
			'lib_form.html#form_textarea',
			'lib_form.html#form_submit',
			'lib_form.html#form_reset',
			'lib_form.html#form_button',
			'lib_form.html#form_radio',
			'lib_form.html#form_checkbox',
			'lib_form.html#form_select',
			'lib_form.html#form_multiple',
			'lib_form.html#form_file',
		'lib_ftp',
			'lib_ftp.html#ftp_import',
			'lib_ftp.html#ftp_connect',
			'lib_ftp.html#ftp_create_folder',
			'lib_ftp.html#ftp_delete_folder',
			'lib_ftp.html#ftp_change_folder',
			'lib_ftp.html#ftp_rename',
			'lib_ftp.html#ftp_delete_file',
			'lib_ftp.html#ftp_file_size',
			'lib_ftp.html#ftp_download',
			'lib_ftp.html#ftp_upload',
			'lib_ftp.html#ftp_files',
			'lib_ftp.html#ftp_permission',
		'lib_html5',
			'lib_html5.html#html5_import',
			'lib_html5.html#html5_form_open',
			'lib_html5.html#html5_form_close',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_form_objects',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_contents_edit',
			'lib_html5.html#html5_audio',
			'lib_html5.html#html5_video',
			'lib_html5.html#html5_source',
			'lib_html5.html#html5_embed',
			'lib_html5.html#html5_keygen',
		'lib_image',
			'lib_image.html#image_import',
			'lib_image.html#image_thumb',
			'lib_image.html#image_size',
		'lib_jquery',
			'lib_jquery.html#jquery_import',
			'lib_jquery.html#jquery_open',
			'lib_jquery.html#jquery_close',
			'lib_jquery.html#jquery_ready',
			'lib_jquery.html#jquery_event',
			'lib_jquery.html#jquery_fade',
			'lib_jquery.html#jquery_slide',
			'lib_jquery.html#jquery_toggle',
			'lib_jquery.html#jquery_hide',
			'lib_jquery.html#jquery_show',
			'lib_jquery.html#jquery_animate',
			'lib_jquery.html#jquery_ajax',
			'lib_jquery.html#jquery_css',
			'lib_jquery.html#jquery_attr',
			'lib_jquery.html#jquery_func',
			'lib_jquery.html#jquery_code',
		'lib_json',
			'lib_json.html#json_import',
			'lib_json.html#json_encode',
			'lib_json.html#json_decode',
		'lib_method',
			'lib_method.html#method_import',
			'lib_method.html#method_post',
			'lib_method.html#method_get',
			'lib_method.html#method_request',
			'lib_method.html#method_files',
		'lib_pagination',
			'lib_pagination.html#pag_import',
			'lib_pagination.html#pag_settings',
			'lib_pagination.html#pag_create',
		'lib_perm',
			'lib_perm.html#perm_import',
			'lib_perm.html#perm_process',
			'lib_perm.html#perm_page',
		'lib_reg',
			'lib_reg.html#reg_import',
			'lib_reg.html#reg_match',
			'lib_reg.html#reg_replace',
		'lib_search',
			'lib_search.html#search_import',
			'lib_search.html#search_get',
			'lib_search.html#search_filter',
		'lib_sec',
			'lib_sec.html#sec_import',
			'lib_sec.html#sec_nc_encode',
			'lib_sec.html#sec_nail_encode',
			'lib_sec.html#sec_injection_encode',
			'lib_sec.html#sec_html_encode',
		'lib_sess',
			'lib_sess.html#sess_import',
			'lib_sess.html#sess_insert',
			'lib_sess.html#sess_select',
			'lib_sess.html#sess_select_all',
			'lib_sess.html#sess_delete',
			'lib_sess.html#sess_delete_all',
		'lib_upload',
			'lib_upload.html#upload_import',
			'lib_upload.html#upload_settings',
			'lib_upload.html#upload_start',
			'lib_upload.html#upload_info',
			'lib_upload.html#upload_error',

		'lib_uri',
			'lib_uri.html#uri_import',
			'lib_uri.html#uri_get',
			'lib_uri.html#uri_segment',
			'lib_uri.html#uri_segment_array',
			'lib_uri.html#uri_total_segment',
		'lib_user',
			'lib_user.html#user_import',
			'lib_user.html#user_config',
			'lib_user.html#user_register',
			'lib_user.html#user_login',
			'lib_user.html#user_update',
			'lib_user.html#user_logout',
			'lib_user.html#user_is_login',
			'lib_user.html#user_data',
			'lib_user.html#user_forgot_password',
			'lib_user.html#user_activation_complete',
			'lib_user.html#user_error',
			'lib_user.html#user_success',
		'lib_val',
			'lib_val.html#val_import',
			'lib_val.html#val_params',
			'lib_val.html#val_rules',
			'lib_val.html#val_nval',
			'lib_val.html#val_error',
			'lib_val.html#val_post_back',
		'lib_xml',
			'lib_xml.html#xml_import',
			'lib_xml.html#xml_create',
			'lib_xml.html#xml_add_element',
			'lib_xml.html#xml_remove_element',
			'lib_xml.html#xml_add_attr',
			'lib_xml.html#xml_remove_attr',
			'lib_xml.html#xml_get_attr',
			'lib_xml.html#xml_add_content',
			'lib_xml.html#xml_get_content',
			'lib_xml.html#xml_get_content',
			'lib_xml.html#xml_get_content',
			'lib_xml.html#xml_save',
			'lib_xml.html#xml_load',
			'lib_xml.html#xml_path',		
			
		'tool_ajax',
			'tool_ajax.html#ajax_import',
			'tool_ajax.html#ajax_json_send_back',
			'tool_ajax.html#ajax_send_back',
		'tool_array',
			'tool_array.html#array_import',
			'tool_array.html#array_pos_change',
			'tool_array.html#array_pos_reverse',
			'tool_array.html#array_delete_element',
			'tool_array.html#multi_key_array',
			'tool_array.html#array_keyval',
			'tool_array.html#array_object',
		'tool_builder',
			'tool_builder.html#builder_import',
			'tool_builder.html#xml_builder',
			'tool_builder.html#list_builder',
			'tool_builder.html#table_builder',
		'tool_captcha',
			'tool_captcha.html#captcha_import',
			'tool_captcha.html#create_captcha',
			'tool_captcha.html#get_captcha_code',
		'tool_cleaner',
			'tool_cleaner.html#cleaner_import',
			'tool_cleaner.html#cleaner',
		'tool_converter',
			'tool_converter.html#converter_import',
			'tool_converter.html#char_converter',
			'tool_converter.html#accent_converter',
			'tool_converter.html#url_word_converter',
			'tool_converter.html#case_converter',
			'tool_converter.html#charset_converter',
		'tool_creator',
			'tool_creator.html#creator_import',
			'tool_creator.html#password_creator',
		'tool_datetime',
			'tool_datetime.html#datetime_import',
			'tool_datetime.html#standart_time',
			'tool_datetime.html#current_time',
			'tool_datetime.html#current_date',
			'tool_datetime.html#current_date_time',
			'tool_datetime.html#set_time',
			'tool_datetime.html#set_date',
		'tool_email',
			'tool_email.html#email_import',
			'tool_email.html#email',
			'tool_email.html#imap_email',
		'tool_encoder',
			'tool_encoder.html#encoder_import',
			'tool_encoder.html#encoder',
			'tool_encoder.html#php_tag_encoder',
			'tool_encoder.html#nail_encoder',
			'tool_encoder.html#foreign_char_encoder',
		'tool_filter',
			'tool_filter.html#filter_import',
			'tool_filter.html#word_filter',
		'tool_formatter',
			'tool_formatter.html#formatter_import',
			'tool_formatter.html#byte_formatter',
			'tool_formatter.html#money_formatter',
			'tool_formatter.html#time_formatter',
		'tool_html',
			'tool_html.html#html_import',
			'tool_html.html#html_element',
			'tool_html.html#multi_attr',
			'tool_html.html#heading',
			'tool_html.html#font',
			'tool_html.html#parag',
			'tool_html.html#bold',
			'tool_html.html#strong',
			'tool_html.html#italic',
			'tool_html.html#underline',
			'tool_html.html#overline',
			'tool_html.html#undertext',
			'tool_html.html#overtext',
			'tool_html.html#anchor',
			'tool_html.html#mailto',
			'tool_html.html#image',
			'tool_html.html#space',
			'tool_html.html#br',
			'tool_html.html#meta',
		'tool_limiter',
			'tool_limiter.html#limitter_import',
			'tool_limiter.html#word_limiter',
			'tool_limiter.html#char_limiter',
		'tool_parser',
			'tool_parser.html#parser_import',
			'tool_parser.html#parser',
		'tool_reader',
			'tool_reader.html#reader_import',
			'tool_reader.html#rss_reader',
		'tool_repeater',
			'tool_repeater.html#repeater_import',
			'tool_repeater.html#repeater',
		'tool_rounder',
			'tool_rounder.html#rounder_import',
			'tool_rounder.html#rounder',
		'tool_searcher',
			'tool_searcher.html#searcher_import',
			'tool_searcher.html#searcher',
		'tool_sound',
			'tool_sound.html#sound_import',
			'tool_sound.html#add_sound',
		'tool_string',
			'tool_string.html#string_import',
			'tool_string.html#mtrim',
			'tool_string.html#trim_slashes',
			'tool_string.html#uppercase',
			'tool_string.html#lowercase',
			'tool_string.html#titlecase',
			'tool_string.html#sub_string',
			'tool_string.html#string_search',
			'tool_string.html#string_reshuffle',
			'tool_string.html#string_recurrent_count',
			'tool_string.html#string_placement',
		'tool_symbol',
			'tool_symbol.html#symbol_import',
			'tool_symbol.html#symbol',
		'tool_uploader',
			'tool_uploader.html#uploader_import',
			'tool_uploader.html#sql_file_uploader',
			'tool_uploader.html#file_uploader',
			
		'config_library',
		'config_autoload',
		'config_cache',
		'config_captcha',
		'config_cookie',
		'config_curl',
		'config_database',
		'config_datetime',
		'config_doctype',
		'config_email',
		'config_encode',
		'config_foreignchars',
		'config_log',
		'config_headers',
		'config_htaccess',
		'config_ini',
		'config_language',
		'config_masterpage',
		'config_permission',
		'config_regex',
		'config_repair',
		'config_route',
		'config_security',
		'config_session',
		'config_symbols',
		'config_upload',
		'config_uri',
		'config_user',
		
	];
	
	if(getParameterByName('search-text') != "")
	{
		var result = '';
		var string = '';
		var total = 0;
		var word = getParameterByName('search-text');
		
		for(var i = 0; i < searchKeys.length; i++)
		{
			$('#search-result').html('<b>Veri Aranıyor...</b>');
			string = searchKeys[i].toLowerCase();
			
			word = word.toLowerCase();
			
			if(string.indexOf(word) > -1)
			{
				var reWord = searchKeys[i].replace(word, '<strong style="color:#333">'+word+'</strong>');
				
				if(searchVals[i].indexOf('.html') == -1)
					searchVals[i] += '.html';
					
				result += '<div type="search"><a class="searchfont" href="' + searchVals[i] + '">' + reWord + '</a></div>';	
				total++;
			}	
		}	
		
		if(result != '')
		{
			$('#total-result').html('Arama tamamlandı, eşleşen(' + total + ') veri bulundu.');
			$('#search-result').html(result);
		}
		else
		{
			$('#total-result').html('Arama tamamlandı, eşleşen veri bulunamadı!');
			$('#search-result').html('<b>Sonuç bulunamadı!</b>');   
		}
	}
	else
	{
		$('#total-result').html('Arama tamamlandı, eşleşen veri bulunamadı!');
		$('#search-result').html('<b>Sonuç bulunamadı!</b>');  
	}
		
});
// JavaScript Document